version: '3.8'
services:
  frontend:
    image: getkarma/money_app:frontend
    container_name: money-app-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:4000
    networks:
      - money-app-network

  backend:
    image: getkarma/money_app:backend
    container_name: money-app-backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/moneyapp
    networks:
      - money-app-network
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: money-app-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=moneyapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - money-app-network

networks:
  money-app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local