version: '3.8'
services:
  frontend:
    image: yourusername/money-app-frontend:latest
    container_name: money-app-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:4000
    networks:
      - money-app-network

  backend:
    image: yourusername/money-app-backend:latest
    container_name: money-app-backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/moneyapp
      - NODE_ENV=production
    networks:
      - money-app-network
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: money-app-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - money-app-network

networks:
  money-app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local 