CREATE TABLE IF NOT EXISTS user_data (
  user_id TEXT PRIMARY KEY,
  expenses JSONB NOT NULL DEFAULT '{}',
  subscriptions JSONB NOT NULL DEFAULT '{}',
  money_info JSONB NOT NULL DEFAULT '{}',
  incomes JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
); 